### Criar novo usuário com senha criptografada e role USER
POST https://silver-space-yodel-7v9jw54rj4v7fxpp6-8080.app.github.dev
Content-Type: application/json

{
  "username": "rafael",
  "password": "senha123"
}

### Listar usuários
GET https://silver-space-yodel-7v9jw54rj4v7fxpp6-8080.app.github.dev
Accept: application/json
